# Generated by Django 2.2.5 on 2020-03-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20200311_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='main_class',
            field=models.CharField(blank=True, choices=[('a', 'Academico'), ('l', 'Literatura'), ('n', 'No ficción')], help_text='Clasificacion principal del libro', max_length=1),
        ),
    ]
