# Generated by Django 2.2.5 on 2020-03-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_bookinstance_main_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('member_num', models.CharField(max_length=8)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_num', models.CharField(max_length=15)),
            ],
        ),
    ]
