# Generated by Django 2.2.5 on 2020-03-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('retornar', 'marcar como retornado'),)},
        ),
    ]
