# Generated by Django 2.2.5 on 2020-03-17 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_auto_20200317_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Book', verbose_name='Libro'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(max_length=200, verbose_name='Editorial'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='main_class',
            field=models.CharField(blank=True, choices=[('a', 'Academico'), ('l', 'Literatura'), ('n', 'No ficción')], help_text='(Academico, Literatura, No ficción)', max_length=1, verbose_name='Estantería'),
        ),
    ]
