# Generated by Django 2.2.5 on 2020-03-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_auto_20200317_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
