# Generated by Django 2.2.5 on 2020-03-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_book_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='counter',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
