# Generated by Django 2.2.5 on 2020-03-20 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0018_auto_20200317_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ID de usuario'),
        ),
    ]
