# Generated by Django 2.2.5 on 2020-03-20 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0019_member_borrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_num',
        ),
        migrations.AddField(
            model_name='member',
            name='memberID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ID de'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_num',
            field=models.CharField(max_length=15, verbose_name='No Telefono'),
        ),
    ]
