# Generated by Django 2.2.5 on 2020-03-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_bookinstance_loan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='loan_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
