# Generated by Django 2.2.5 on 2020-03-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_auto_20200324_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
