# Generated by Django 2.2.5 on 2020-03-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_auto_20200328_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pub_date']},
        ),
    ]
