# Generated by Django 2.2.5 on 2020-03-29 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0028_auto_20200329_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Book', verbose_name='Libro')),
                ('mentor', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Referente')),
            ],
        ),
    ]
