# Generated by Django 2.2.5 on 2020-03-29 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0029_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='mentor',
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Referente'),
            preserve_default=False,
        ),
    ]
