# Generated by Django 2.2.5 on 2020-03-29 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_auto_20200329_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Member', verbose_name='Referente'),
        ),
    ]
