# Generated by Django 2.2.5 on 2020-03-29 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0031_auto_20200329_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='contact_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Referente'),
        ),
    ]
