# Generated by Django 2.2.5 on 2020-03-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0032_auto_20200329_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='E-mail de contacto'),
        ),
    ]
